image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/nc-edu/travel-planner .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/nc-edu/travel-planner

openshift-deploy:
  stage: deploy
  script:
    - |
        if [ ! -f "oc/oc" ] ; then
          apk add --update curl && rm -rf /var/cache/apk/*
          curl -O -L https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz;
          tar -xf openshift-origin-client-tools*.tar.gz;
          mkdir -pv oc
          cp -v openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit/oc oc/
        else
          echo "oc bin from cache"
        fi
        
    - cp -v oc/oc "$target/usr/local/bin/oc"
    - oc version
    - oc login $OPENSHIFT_SERVER —token=$OPENSHIFT_TOKEN —insecure-skip-tls-verify=true
    - oc project $OPENSHIFT_REVIEW_PROJECT
    - oc delete all -l app=$CI_COMMIT_REF_SLUG -n $OPENSHIFT_REVIEW_PROJECT
    - oc delete pvc -l app=$CI_COMMIT_REF_SLUG -n $OPENSHIFT_REVIEW_PROJECT
    - export DOCKER_TAG="${CI_COMMIT_REF_SLUG}_latest"
    - oc new-app -n $OPENSHIFT_REVIEW_PROJECT -f openshift/template.yml -p APPLICATION_NAME=$CI_COMMIT_REF_SLUG -p DOCKER_IMAGE_TAG=$DOCKER_TAG