image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  APP: $CI_PROJECT_NAME-app
  PROJ_NAME: $CI_PROJECT_NAME

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
  - docker build -t registry.gitlab.com/nc-edu/travel-planner .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/nc-edu/travel-planner

k8s-deploy:
  image: ayufan/openshift-cli
  stage: deploy
  before_script:
    - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify
    - oc project $PROJ_NAME 2> /dev/null || oc new-project $PROJ_NAME
  script:
    - oc delete all -l app=$APP
    - oc delete pvc -l app=$APP
    - oc delete all --all
    - oc delete all --selector app=$APP
    - oc delete secret registry
    - oc delete secret app
    - oc secrets new-dockercfg registry --docker-server=registry.gitlab.com --docker-username=$GITLAB_USER --docker-password=$GITLAB_PASS --docker-email=$GITLAB_EMAIL
    - oc secrets new-dockercfg app --docker-server=gitlab.com --docker-username=$GITLAB_USER --docker-password=$GITLAB_PASS --docker-email=$GITLAB_EMAIL
    - oc secrets add serviceaccount/default secrets/registry --for=pull
    - oc secrets add serviceaccount/default secrets/app --for=pull
    - oc get services $APP 2> /dev/null || oc new-app --name=$APP --docker-image="registry.gitlab.com/nc-edu/travel-planner:latest"
    - oc get routes $APP 2> /dev/null || oc expose dc/$APP --port=8080
    - oc create route edge nc --service=$APP
    - oc get routes
