image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/nc-edu/travel-planner .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/nc-edu/travel-planner

openshift-deploy:
  stage: deploy
  script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - curl -L  https://github.com/openshift/origin/releases/download/v1.3.2/openshift-origin-client-tools-v1.3.2-ac1d579-linux-64bit.tar.gz | tar -xz
    - sudo cp openshift-origin-client-tools-*/oc /usr/local/bin/.
    - oc version
    - oc login $OPENSHIFT_SERVER —token=$OPENSHIFT_TOKEN —insecure-skip-tls-verify=true
    - oc project $OPENSHIFT_REVIEW_PROJECT
    - oc delete all -l app=$CI_COMMIT_REF_SLUG -n $OPENSHIFT_REVIEW_PROJECT
    - oc delete pvc -l app=$CI_COMMIT_REF_SLUG -n $OPENSHIFT_REVIEW_PROJECT
    - export DOCKER_TAG="${CI_COMMIT_REF_SLUG}_latest"
    - oc new-app -n $OPENSHIFT_REVIEW_PROJECT -f openshift/template.yml -p APPLICATION_NAME=$CI_COMMIT_REF_SLUG -p DOCKER_IMAGE_TAG=$DOCKER_TAG